In [3]:
# NumPy is a python library used for working with arrays.

# It also has functions for working in domain of linear algebra, fourier transform, and matrices.

# NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

# NumPy stands for Numerical Python.


## Why is NumPy Faster Than Lists?
# NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

# This behavior is called locality of reference in computer science.

# This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.


import numpy 
a= numpy.array([1,2,3])
print (a)



[1 2 3]


In [5]:
import numpy as np
a= np.array([1,2,3,4,5,6])
print (a)

[1 2 3 4 5 6]


In [6]:
#printing the  Numpy version 
print (np.__version__)

1.18.4


In [7]:
#Creating the Numpy array and type()
a=np.array([1,2,3])
print (a)
print (type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [9]:
#Array with the tuple
a= np.array((1,2,3,4,5,6))
print (a)

[1 2 3 4 5 6]


In [12]:
## Diemntios of the Numpy array 
# 0D
a= np.array(1)
print (a)
print (a.ndim)

1
0


In [13]:
# Numpy 1D arrray
a= np.array([1])
print (a)
print (a.ndim)

[1]
1


In [14]:
#Numpy 2D array
a= np.array([[1,2,3], [4,5,6]])
print (a)
print (a.ndim)

[[1 2 3]
 [4 5 6]]
2


In [15]:
#Numpy 3D array
a= np.array([[[1,2,3],[4,5,6]], [[7,8,9],[7,4,4]]])
print (a)
print (a.ndim)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [7 4 4]]]
3


In [16]:
#Numpy array dimention
a= np.array(10)
b= np.array([1,2,3,4,5,6])
c= np.array([[1,2,3],[7,8,9]])
d= np.array([[[1,2,3,4], [7,8,9,4]], [[7,8,9,4],[7,8,9,4]]])
print (a.ndim)
print (b.ndim)
print (c.ndim)
print (d.ndim)

0
1
2
3


In [18]:
#You can define the dimention of tha array when you creat them using ndmin
a= np.array([1], ndmin=5)
print (a)
print (a.ndim)

[[[[[1]]]]]
5


In [19]:
## Numpy array Indexing 
# In numpy each and evry elements have index staring from 0 just like list array
a= np. array([1,2,3,4,5,6])
print (a[3])


4


In [20]:
#Arithmatical opeation between array indexes
a= np.array([1,2,3,4,5,6])
print (a[0]+ a[4])

6


In [27]:
#Array indexing with the 2D array a[raw, column]

a = np.array([[1,2,3,4,5,6], [7,8,9,4,5,6]])
print ("Array [1st raw, 2nd column]:", a[1,4])

Array [1st raw, 2nd column]: 5


In [34]:
# Array indexing with the 3D array
a = np.array([[[1,2,3,4], [7,8,9,4]], [[7,4,1,8], [7,8,9,4]]])
print (a)
print (a[1,1,3])

# And this is why:

# The first number represents the first dimension, which contains two arrays:
# [[1, 2, 3,4], [7,8,9,4]],
# and:
# [[7,4,1,8],  [7,8,9,4]]
# Since we selected 1, we are left with the first array:
# [[7,4,1,8], [7,8,9,4]]

# The second number represents the second dimension, which also contains two arrays:
# [7,4,1,8]
# and:
# [7,8,9,4]
# Since we selected 1, we are left with the second array:
# [7,8,9,4]
# and the element is 3 which is 4

[[[1 2 3 4]
  [7 8 9 4]]

 [[7 4 1 8]
  [7 8 9 4]]]
4


In [36]:
## Array Slicing
# Slicing means to print the array from start to end [start: end]
import numpy as np
a= np.array([1,2,3,4,5,6])
print (a[1:4])

[2 3 4]


In [38]:
# Array slicing examplse 
a= np.array([1,2,3,4,5,6,7,8,9])
print (a[2:6])
print (a[1:9:2])  # [start: stop: jump]
print (a[5:])
print (a[:5])
print (a[::2])

[3 4 5 6]
[2 4 6 8]
[6 7 8 9]
[1 2 3 4 5]
[1 3 5 7 9]


In [39]:
# Array  slicing with the 
import numpy as np
a= np.array([[1,2,3,4,5,6], [7,8,9,4,5,6]])
print (a[1, 1:4])   # 1st raw 1: 4


[8 9 4]


In [40]:
a= np.array([[1,2,3,4,5,6], [7,8,9,4,5,6]])
print (a[0:2, 2])   # from the both of the raw 2nd elements

[3 9]


In [41]:
a= np.array([[1,2,3,4,5,6], [7,8,9,4,5,6]])
print (a[0:2, 2:4])   # from the both of the raw, display 2 to 4

[[3 4]
 [9 4]]


In [1]:
## Numpy datatype
# By default Python have these data types:

# strings - used to represent text data, the text is given under quote marks. eg. "ABCD"
# integer - used to represent integer numbers. eg. -1, -2, -3
# float - used to represent real numbers. eg. 1.2, 42.42
# boolean - used to represent True or False.
# complex - used to represent a number in complex plain. eg. 1.0 + 2.0j, 1.5 + 2.5j


In [12]:
## Numpy split 
# Numpy array splitting is the reverse of the concatinate 
import numpy as np
a= np.array([1,2,3,4,5,6])
a_new= np.array_split(a, 3)
print (a_new)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [11]:
# Numpy array split 
a= np.array([1,2,3,4,5,6,7,8,9])
a_new = np.array_split(a, 4)
print (a_new)


[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [15]:
#2D array splitting 
a= np.array([[1,2,3], [7,8,90], [7,4,1], [8,5,2]])
a_new= np.array_split(a,3)
print (a_new)

[array([[ 1,  2,  3],
       [ 7,  8, 90]]), array([[7, 4, 1]]), array([[8, 5, 2]])]


In [16]:
# Numpy 3D array splitting 
a= np.array([[[1,2,3], [1,7,8]], [[7,4,1], [8,5,2]]])
a_new= np.array_split(a,2)
print (a_new)

[array([[[1, 2, 3],
        [1, 7, 8]]]), array([[[7, 4, 1],
        [8, 5, 2]]])]


In [18]:
# Numpy has an attribute for the horizontally split the array called "hsplit"
# 1D array hsplit
a= np.array([[1,2], [4,1], [7,8], [8,5], [6,3], [5,2]])
a_new = np.hsplit(a,2)
print (a_new)

[array([[1],
       [4],
       [7],
       [8],
       [6],
       [5]]), array([[2],
       [1],
       [8],
       [5],
       [3],
       [2]])]


In [20]:
#3D array hsplit
a= np.array([[[1,2,3], [7,8,9]], [[7,8,9], [7,4,1]]])
a_new= np.hsplit(a, 2)
print (a_new)

[array([[[1, 2, 3]],

       [[7, 8, 9]]]), array([[[7, 8, 9]],

       [[7, 4, 1]]])]


In [26]:
# Numpy vsplit attributes
a= np.array([[1,2], [7,8], [7,4], [8,5], [9,6], [8,5]])
a_new= np.vsplit(a,2)
print (a_new)

[array([[1, 2],
       [7, 8],
       [7, 4]]), array([[8, 5],
       [9, 6],
       [8, 5]])]


In [28]:
## Numpy array serching using where() attributes
a= np.array([1,2,3,4,5,6,7,8,9])
x= np.where(a==5)
print (x)

(array([4]),)


In [29]:
# Even number finding form the array (Note : that will return the location of the Even array elements)
a= np.array([1,2,3,4,5,6,7,8,9])
x= np.where(a%2==0)
print(x)

(array([1, 3, 5, 7]),)


In [30]:
# /numpy finding the odd number array position 
a= np.array([1,2,3,4,5,6,7,8,9])
x= np.where(a%2==1)
print (x)

(array([0, 2, 4, 6, 8]),)


In [31]:
# Numpy has "Searchsorted" attribute to serch the indexing of the array element 
a= np.array([1,2,3,4,5,6,7,8,9])
x = np.searchsorted(a,5)
print (x)

4


In [33]:
# Numpy serchsorted from the right side 
a= np.array([1,2,3,4,5,6,7,8,9])
x= np.searchsorted(a, 5, side= 'right')
print (x)

5


In [34]:
## Numpy arary sorting 
a= np.array([7,5,3,1,-9,0,5,8])
a_new= np.sort (a)
print (a_new)

[-9  0  1  3  5  5  7  8]


In [35]:
# Numpys rting array sorting 
a= np.array(["Cat", "Doc", "Apple", "Banana"])
print (np.sort(a))

['Apple' 'Banana' 'Cat' 'Doc']


In [36]:
# Numpy 2D array sorting
a= np.array([[7,4,1], [8,5,2]])
print (np.sort(a))

[[1 4 7]
 [2 5 8]]


In [2]:
## Numpy array filter 
import numpy as np
a= np.array([1,2,3,4,5,6])
x= [True, True, True, False,True, False]
print (a[x])

[1 2 3 5]


In [10]:
# Numpy filtering even numbers 
a= np.array([1,2,3,4,5,6,7,8,9])
even_number=[]
for i in a:
    if i%2==0:
      even_number.append(i)
    
print (even_number)

[2, 4, 6, 8]


In [11]:
## Numpy random library
from numpy import random
a= random.randint(100)
print (a)

85


In [12]:
#Numpy random number for perticular size array from the limit

from numpy import random 
a= random.randint(100, size=10)
print (a)

[17 48 43 49 10  1 84 12 20 72]


In [14]:
# Numpy 2D array of the random number between range 
from numpy import random
a= random.randint(100, size=(3,4))
print (a)

[[39 41  7 81]
 [86 72 95 41]
 [89 40  1 14]]


In [15]:
# float random number
from numpy import random
a= random.rand()
print (a)

0.8826978419012461


In [16]:
#Floar random number of the 10 array members
from numpy import random
a= random.rand(10)
print (a)

[0.87688534 0.8092257  0.6338828  0.11774989 0.01041293 0.27395906
 0.01256424 0.82872192 0.38234929 0.1570516 ]


In [17]:
#2D array of the float random number
from numpy import random
a= random.rand(3,3)
print (a)

[[0.03804317 0.64484196 0.98020227]
 [0.44104341 0.30222209 0.9919564 ]
 [0.5230096  0.55233811 0.20238348]]
